
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Khalid
 */
public class DetailPesan extends javax.swing.JFrame {

    /**
     * Creates new form DetailPesan
     */
    String idRute = "";
    String namaDepan = "";
    String namaBelakang = "";
    String Alamat = "";
    String NoHP = "";
    int Harga = 0;
    public DetailPesan(String id_rute, String nama_depan, String nama_belakang, String alamat, String no_hp) {
        initComponents();
        
        this.idRute = id_rute;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        this.idRute = id_rute;
        this.namaDepan = nama_depan;
        this.namaBelakang = nama_belakang;
        this.Alamat = alamat;
        this.NoHP = no_hp;
        
        tBayar.setBorder(BorderFactory.createCompoundBorder(
        tBayar.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tKembali.setBorder(BorderFactory.createCompoundBorder(
        tKembali.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
           try {
            //membuat statemen pemanggilan data pada table tblGaji dari database
            Statement stat = (Statement) Koneksi.configDB().createStatement();
            String sql = "SELECT * FROM rute INNER JOIN maskapai ON rute.id_maskapai = maskapai.id_maskapai WHERE id_rute = '"+id_rute+"'";
            ResultSet res = stat.executeQuery(sql);

            //penelusuran baris pada tabel tblGaji dari database
            while (res.next()) {
                lNamaMaskapai.setText(res.getString("nama_maskapai"));
                lAsal.setText(res.getString("asal"));
                lTujuan.setText(res.getString("tujuan"));
                lKelas.setText(res.getString("kelas"));
                lHarga.setText(Koneksi.Rupiah(res.getInt("harga")));
                this.Harga = res.getInt("harga");
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
        lNamaDepan.setText(nama_depan);
        lNamaBelakang.setText(nama_belakang);
        lAlamat.setText(alamat);
        lNomorHP.setText(no_hp);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lNamaMaskapai = new javax.swing.JLabel();
        lAsal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lTujuan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lKelas = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lNamaDepan = new javax.swing.JLabel();
        lNamaBelakang = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lAlamat = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lNomorHP = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lHarga = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tBayar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        tKembali = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(9, 120, 165));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 550, 960, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dot2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-white.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circle2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/header2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 950, 240));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_traveler_18px.png"))); // NOI18N
        jLabel5.setText("Data Penumpang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Maskapai");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        lNamaMaskapai.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lNamaMaskapai.setForeground(new java.awt.Color(12, 67, 90));
        lNamaMaskapai.setText("jLabel7");
        getContentPane().add(lNamaMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lAsal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lAsal.setForeground(new java.awt.Color(12, 0, 0));
        lAsal.setText("jLabel7");
        getContentPane().add(lAsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Asal");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_direction_25px.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        lTujuan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lTujuan.setForeground(new java.awt.Color(12, 0, 0));
        lTujuan.setText("jLabel7");
        getContentPane().add(lTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("Tujuan");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        lKelas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lKelas.setForeground(new java.awt.Color(12, 0, 0));
        lKelas.setText("jLabel7");
        getContentPane().add(lKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("Kelas");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_around_the_globe_18px.png"))); // NOI18N
        jLabel15.setText("Data Pesanan");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setText("Nama Depan");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        lNamaDepan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lNamaDepan.setForeground(new java.awt.Color(12, 0, 0));
        lNamaDepan.setText("jLabel7");
        getContentPane().add(lNamaDepan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        lNamaBelakang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lNamaBelakang.setForeground(new java.awt.Color(12, 0, 0));
        lNamaBelakang.setText("jLabel7");
        getContentPane().add(lNamaBelakang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setText("Nama Belakang");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        lAlamat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lAlamat.setForeground(new java.awt.Color(12, 0, 0));
        lAlamat.setText("jLabel7");
        getContentPane().add(lAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setText("Alamat");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setText("Nomor HP");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        lNomorHP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lNomorHP.setForeground(new java.awt.Color(12, 0, 0));
        lNomorHP.setText("jLabel7");
        getContentPane().add(lNomorHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel24.setText("Total Pembayaran");

        lHarga.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lHarga.setForeground(new java.awt.Color(12, 67, 90));
        lHarga.setText("jLabel25");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel26.setText("Uang Bayar");

        tBayar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tBayar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBayarActionPerformed(evt);
            }
        });
        tBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tBayarKeyReleased(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel27.setText("Kembalian");

        tKembali.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(12, 67, 90));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_checkout_16px.png"))); // NOI18N
        jButton1.setText("Bayar");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tBayar)
                    .addComponent(jSeparator1)
                    .addComponent(tKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(lHarga)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lHarga)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 230, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBayarActionPerformed

    private void tBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tBayarKeyReleased
        // TODO add your handling code here:
        int bayar = Integer.parseInt(tBayar.getText());
        if(bayar>Harga){
            int kembalian = bayar - Harga;
            tKembali.setText(Integer.toString(kembalian));
        }else{
            tKembali.setText("0");
        }
    }//GEN-LAST:event_tBayarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        HasilPesan a = new HasilPesan(this.idRute,this.namaDepan,this.namaBelakang,this.Alamat,this.NoHP);
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailPesan(null,null,null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lAlamat;
    private javax.swing.JLabel lAsal;
    private javax.swing.JLabel lHarga;
    private javax.swing.JLabel lKelas;
    private javax.swing.JLabel lNamaBelakang;
    private javax.swing.JLabel lNamaDepan;
    private javax.swing.JLabel lNamaMaskapai;
    private javax.swing.JLabel lNomorHP;
    private javax.swing.JLabel lTujuan;
    private javax.swing.JTextField tBayar;
    private javax.swing.JTextField tKembali;
    // End of variables declaration//GEN-END:variables
}
