
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Khalid
 */
public class HasilPesan extends javax.swing.JFrame {

    /**
     * Creates new form HasilPesan
     */
    String idRute = "";
    String namaDepan = "";
    String namaBelakang = "";
    String Alamat = "";
    String NoHP = "";

    public HasilPesan(String id_rute, String nama_depan, String nama_belakang, String alamat, String no_hp) {
        initComponents();
        this.idRute = id_rute;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        this.idRute = id_rute;
        this.namaDepan = nama_depan;
        this.namaBelakang = nama_belakang;
        this.Alamat = alamat;
        this.NoHP = no_hp;
        try {
            //membuat statemen pemanggilan data pada table tblGaji dari database
            Statement stat = (Statement) Koneksi.configDB().createStatement();
            String sql = "SELECT * FROM rute INNER JOIN maskapai ON rute.id_maskapai = maskapai.id_maskapai WHERE id_rute = '" + id_rute + "'";
            ResultSet res = stat.executeQuery(sql);

            //penelusuran baris pada tabel tblGaji dari database
            while (res.next()) {
                Random random = new Random();
                lKodeBooking.setText("#TVG"+Integer.toString(random.nextInt(9999 + 1 - 1000) + 1000));
                lNamaMaskapai.setText(res.getString("nama_maskapai"));
                lAsal.setText(res.getString("asal"));
                lTujuan.setText(res.getString("tujuan"));
                lKelas.setText(res.getString("kelas"));
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
        lNamaDepan.setText(nama_depan);
        lNamaBelakang.setText(nama_belakang);
        lAlamat.setText(alamat);
        lNomorHP.setText(no_hp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lNamaMaskapai = new javax.swing.JLabel();
        lAsal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lTujuan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lKelas = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lNomorHP = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lAlamat = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lNamaDepan = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lNamaBelakang = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        lKodeBooking = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dot2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(9, 120, 165));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 550, 960, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-white.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circle2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/header2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 950, 240));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_ok_40px.png"))); // NOI18N
        jLabel5.setText("Pemesanan Berhasil");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_around_the_globe_18px.png"))); // NOI18N
        jLabel15.setText("Data Pesanan");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Maskapai");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        lNamaMaskapai.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lNamaMaskapai.setText("jLabel7");
        getContentPane().add(lNamaMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        lAsal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lAsal.setForeground(new java.awt.Color(12, 0, 0));
        lAsal.setText("jLabel7");
        getContentPane().add(lAsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Asal");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_direction_25px.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        lTujuan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lTujuan.setForeground(new java.awt.Color(12, 0, 0));
        lTujuan.setText("jLabel7");
        getContentPane().add(lTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("Tujuan");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        lKelas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lKelas.setForeground(new java.awt.Color(12, 0, 0));
        lKelas.setText("jLabel7");
        getContentPane().add(lKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("Kelas");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, -1, -1));

        lNomorHP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lNomorHP.setForeground(new java.awt.Color(12, 0, 0));
        lNomorHP.setText("jLabel7");
        getContentPane().add(lNomorHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setText("Nomor HP");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        lAlamat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lAlamat.setForeground(new java.awt.Color(12, 0, 0));
        lAlamat.setText("jLabel7");
        getContentPane().add(lAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setText("Alamat");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        lNamaDepan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lNamaDepan.setForeground(new java.awt.Color(12, 0, 0));
        lNamaDepan.setText("jLabel7");
        getContentPane().add(lNamaDepan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setText("Nama Depan");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_traveler_18px.png"))); // NOI18N
        jLabel7.setText("Data Penumpang");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setText("Nama Belakang");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        lNamaBelakang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lNamaBelakang.setForeground(new java.awt.Color(12, 0, 0));
        lNamaBelakang.setText("jLabel7");
        getContentPane().add(lNamaBelakang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 180, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Kode Booking");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        lKodeBooking.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lKodeBooking.setForeground(new java.awt.Color(12, 67, 90));
        lKodeBooking.setText("jLabel7");
        getContentPane().add(lKodeBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jButton1.setBackground(new java.awt.Color(12, 67, 90));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_ticket_15px.png"))); // NOI18N
        jButton1.setText("Pesan Tiket Lagi");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 150, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Dashboard a = new Dashboard();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HasilPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HasilPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HasilPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HasilPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HasilPesan(null, null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lAlamat;
    private javax.swing.JLabel lAsal;
    private javax.swing.JLabel lKelas;
    private javax.swing.JLabel lKodeBooking;
    private javax.swing.JLabel lNamaBelakang;
    private javax.swing.JLabel lNamaDepan;
    private javax.swing.JLabel lNamaMaskapai;
    private javax.swing.JLabel lNomorHP;
    private javax.swing.JLabel lTujuan;
    // End of variables declaration//GEN-END:variables
}
